#!/usr/bin/env python3
"""Build the diabetes Deep Learning notebook for Assignment 03."""
import json, os

def md(s): return {"cell_type":"markdown","metadata":{},"source":s}
def code(s): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":s}

cells=[]

cells.append(md(
"# DỰ ĐOÁN BỆNH TIỂU ĐƯỜNG — DEEP LEARNING (NUMPY & PYTORCH)\n"
"\n"
"**Assignment 03 — Neural Networks and Representation Learning**\n"
"\n"
"**Nội dung theo slide:**\n"
"1. **Part 1:** Triển khai mạng nơ-ron từ đầu bằng **NumPy** (theo slide tutorial *Deep Learning from Scratch with NumPy*)\n"
"2. **Part 2:** Xây dựng mô hình **PyTorch MLP** và thực hiện **3 thí nghiệm bắt buộc**:\n"
"   - *Thí nghiệm 1:* Baseline MLP ($d \\to 64 \\to C$)\n"
"   - *Thí nghiệm 2:* Deeper MLP ($d \\to 64 \\to 32 \\to C$)\n"
"   - *Thí nghiệm 3:* Thử nghiệm tối ưu hoá (Adam vs SGD, các Learning Rate khác nhau)\n"
"3. **Part 3:** Khám phá biểu diễn ẩn (**Representation Learning**) được học bởi mạng nơ-ron\n"
"4. **Part 4:** Lưu mô hình PyTorch tốt nhất (`.pth`) và các chỉ số phục vụ so sánh\n"
"\n"
"---"
))

cells.append(md(
"## 1. Import thư viện & Chuẩn bị môi trường"
))
cells.append(code(
"import matplotlib\n"
"matplotlib.use('Agg')\n"
"import numpy as np\n"
"import pandas as pd\n"
"import matplotlib.pyplot as plt\n"
"import seaborn as sns\n"
"import joblib\n"
"import os\n"
"import time\n"
"\n"
"import torch\n"
"import torch.nn as nn\n"
"import torch.optim as optim\n"
"from torch.utils.data import TensorDataset, DataLoader\n"
"\n"
"from sklearn.metrics import (\n"
"    accuracy_score, precision_score, recall_score, f1_score,\n"
"    roc_auc_score, confusion_matrix, classification_report, RocCurveDisplay\n"
")\n"
"\n"
"sns.set_theme(style='whitegrid', palette='deep')\n"
"plt.rcParams['figure.figsize'] = (10, 6)\n"
"\n"
"RANDOM_STATE = 42\n"
"np.random.seed(RANDOM_STATE)\n"
"torch.manual_seed(RANDOM_STATE)\n"
"\n"
"MODEL_DIR = os.path.join('..', 'models')\n"
"os.makedirs(MODEL_DIR, exist_ok=True)\n"
"\n"
"# Load preprocessed data from Notebook 1\n"
"data = np.load(os.path.join(MODEL_DIR, 'preprocessed_data.npz'))\n"
"X_train_res = data['X_train_res']\n"
"y_train_res = data['y_train_res']\n"
"X_val = data['X_val']\n"
"y_val = data['y_val']\n"
"X_test = data['X_test']\n"
"y_test = data['y_test']\n"
"\n"
"feature_names = joblib.load(os.path.join(MODEL_DIR, 'feature_names.pkl'))\n"
"\n"
"print('PyTorch version:', torch.__version__)\n"
"print('Features (d =', len(feature_names), '):', feature_names)\n"
"print('Train size (SMOTE):', X_train_res.shape)\n"
"print('Val size:', X_val.shape)\n"
"print('Test size:', X_test.shape)"
))

# ============================================================
# PART 1: NUMPY FROM SCRATCH
# ============================================================
cells.append(md(
"---\n"
"# PHẦN 1: TRIỂN KHAI MẠNG NƠ-RON TỪ ĐẦU BẰNG NUMPY\n"
"\n"
"*(Tham chiếu: `int_sys_dev_slide_03_basicML_deepLearning_04.09.pdf`)*\n"
"\n"
"### Kiến trúc: $8 \\to 16 \\to 8 \\to 1$\n"
"- **Layer 1:** $8 \\to 16$, Activation: ReLU\n"
"- **Layer 2:** $16 \\to 8$, Activation: ReLU\n"
"- **Layer 3:** $8 \\to 1$, Activation: Sigmoid\n"
"- **Hàm mất mát:** Binary Cross-Entropy Loss\n"
"- **Tối ưu:** Gradient Descent thủ công qua Backpropagation\n"
"\n"
"$$\\hat{y} = f_3(f_2(f_1(X))) = \\sigma(ReLU(ReLU(XW_1 + b_1)W_2 + b_2)W_3 + b_3)$$"
))

cells.append(md(
"### 1.1. Định nghĩa các hàm kích hoạt (Activation Functions) & Đạo hàm"
))
cells.append(code(
"def relu(z):\n"
"    \"\"\"ReLU activation: max(0, z)\"\"\"\n"
"    return np.maximum(0, z)\n"
"\n"
"def relu_derivative(z):\n"
"    \"\"\"Đạo hàm ReLU theo z: 1 nếu z > 0, 0 nếu z <= 0\"\"\"\n"
"    return (z > 0).astype(float)\n"
"\n"
"def sigmoid(z):\n"
"    \"\"\"Sigmoid activation: 1 / (1 + exp(-z)), clip tránh overflow\"\"\"\n"
"    z_clipped = np.clip(z, -500, 500)\n"
"    return 1.0 / (1.0 + np.exp(-z_clipped))\n"
"\n"
"def binary_cross_entropy(y_true, y_pred, eps=1e-15):\n"
"    \"\"\"BCE Loss: -1/N * sum(y*log(p) + (1-y)*log(1-p))\"\"\"\n"
"    y_pred = np.clip(y_pred, eps, 1 - eps)\n"
"    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))"
))

cells.append(md(
"### 1.2. Lớp NeuralNetwork3Layer bằng NumPy"
))
cells.append(code(
"class NeuralNetworkNumPy:\n"
"    \"\"\"\n"
"    Mạng nơ-ron 3 lớp 8 -> 16 -> 8 -> 1 viết bằng thuần NumPy.\n"
"    \"\"\"\n"
"    def __init__(self, input_dim=8, h1=16, h2=8, output_dim=1, random_state=42):\n"
"        np.random.seed(random_state)\n"
"        # Khởi tạo trọng số He (Kaiming) cho ReLU\n"
"        self.W1 = np.random.randn(input_dim, h1) * np.sqrt(2.0 / input_dim)\n"
"        self.b1 = np.zeros((1, h1))\n"
"        self.W2 = np.random.randn(h1, h2) * np.sqrt(2.0 / h1)\n"
"        self.b2 = np.zeros((1, h2))\n"
"        # Khởi tạo Xavier cho Sigmoid output\n"
"        self.W3 = np.random.randn(h2, output_dim) * np.sqrt(1.0 / h2)\n"
"        self.b3 = np.zeros((1, output_dim))\n"
"        \n"
"    def forward(self, X):\n"
"        \"\"\"Forward propagation, lưu intermediate values cho backward.\"\"\"\n"
"        self.X = X\n"
"        self.Z1 = np.dot(X, self.W1) + self.b1\n"
"        self.H1 = relu(self.Z1)\n"
"        \n"
"        self.Z2 = np.dot(self.H1, self.W2) + self.b2\n"
"        self.H2 = relu(self.Z2)\n"
"        \n"
"        self.Z3 = np.dot(self.H2, self.W3) + self.b3\n"
"        self.y_pred = sigmoid(self.Z3)\n"
"        return self.y_pred\n"
"    \n"
"    def backward(self, y_true, lr=0.01):\n"
"        \"\"\"\n"
"        Backpropagation: tính gradient theo chain rule và cập nhật trọng số.\n"
"        \"\"\"\n"
"        N = y_true.shape[0]\n"
"        y_true = y_true.reshape(-1, 1)\n"
"        \n"
"        # Layer 3: dL/dZ3 = y_pred - y_true (khi dùng BCE + Sigmoid)\n"
"        dZ3 = (self.y_pred - y_true) / N\n"
"        dW3 = np.dot(self.H2.T, dZ3)\n"
"        db3 = np.sum(dZ3, axis=0, keepdims=True)\n"
"        \n"
"        # Layer 2: dL/dZ2 = (dZ3 @ W3.T) * relu'(Z2)\n"
"        dH2 = np.dot(dZ3, self.W3.T)\n"
"        dZ2 = dH2 * relu_derivative(self.Z2)\n"
"        dW2 = np.dot(self.H1.T, dZ2)\n"
"        db2 = np.sum(dZ2, axis=0, keepdims=True)\n"
"        \n"
"        # Layer 1: dL/dZ1 = (dZ2 @ W2.T) * relu'(Z1)\n"
"        dH1 = np.dot(dZ2, self.W2.T)\n"
"        dZ1 = dH1 * relu_derivative(self.Z1)\n"
"        dW1 = np.dot(self.X.T, dZ1)\n"
"        db1 = np.sum(dZ1, axis=0, keepdims=True)\n"
"        \n"
"        # Gradient Descent Step\n"
"        self.W3 -= lr * dW3\n"
"        self.b3 -= lr * db3\n"
"        self.W2 -= lr * dW2\n"
"        self.b2 -= lr * db2\n"
"        self.W1 -= lr * dW1\n"
"        self.b1 -= lr * db1\n"
"        \n"
"    def fit(self, X_train, y_train, X_val, y_val, epochs=500, lr=0.05, batch_size=256):\n"
"        \"\"\"Huấn luyện mạng với Mini-batch Gradient Descent.\"\"\"\n"
"        N = X_train.shape[0]\n"
"        history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}\n"
"        \n"
"        for epoch in range(1, epochs + 1):\n"
"            # Shuffle mini-batch\n"
"            indices = np.random.permutation(N)\n"
"            X_shuffled = X_train[indices]\n"
"            y_shuffled = y_train.values[indices] if hasattr(y_train, 'values') else y_train[indices]\n"
"            \n"
"            for start in range(0, N, batch_size):\n"
"                end = min(start + batch_size, N)\n"
"                xb = X_shuffled[start:end]\n"
"                yb = y_shuffled[start:end]\n"
"                self.forward(xb)\n"
"                self.backward(yb, lr=lr)\n"
"            \n"
"            # Đánh giá sau mỗi epoch\n"
"            train_preds = self.forward(X_train)\n"
"            val_preds = self.forward(X_val)\n"
"            \n"
"            y_tr = y_train.values.reshape(-1, 1) if hasattr(y_train, 'values') else y_train.reshape(-1, 1)\n"
"            y_v = y_val.values.reshape(-1, 1) if hasattr(y_val, 'values') else y_val.reshape(-1, 1)\n"
"            \n"
"            tr_loss = binary_cross_entropy(y_tr, train_preds)\n"
"            v_loss = binary_cross_entropy(y_v, val_preds)\n"
"            tr_acc = accuracy_score(y_tr, (train_preds >= 0.5).astype(int))\n"
"            v_acc = accuracy_score(y_v, (val_preds >= 0.5).astype(int))\n"
"            \n"
"            history['train_loss'].append(tr_loss)\n"
"            history['val_loss'].append(v_loss)\n"
"            history['train_acc'].append(tr_acc)\n"
"            history['val_acc'].append(v_acc)\n"
"            \n"
"            if epoch % 100 == 0 or epoch == 1:\n"
"                print(f\"Epoch {epoch:4d}/{epochs} | Train Loss: {tr_loss:.4f}, Acc: {tr_acc:.4f} | Val Loss: {v_loss:.4f}, Acc: {v_acc:.4f}\")\n"
"        \n"
"        return history\n"
"    \n"
"    def predict_proba(self, X):\n"
"        return self.forward(X)\n"
"    \n"
"    def predict(self, X, threshold=0.5):\n"
"        probs = self.predict_proba(X)\n"
"        return (probs >= threshold).astype(int).ravel()"
))

cells.append(md(
"### 1.3. Huấn luyện mô hình NumPy"
))
cells.append(code(
"nn_numpy = NeuralNetworkNumPy(input_dim=8, h1=16, h2=8, output_dim=1, random_state=RANDOM_STATE)\n"
"print('Bắt đầu huấn luyện mô hình thuần NumPy...')\n"
"start_time = time.time()\n"
"numpy_history = nn_numpy.fit(\n"
"    X_train_res, y_train_res,\n"
"    X_val, y_val,\n"
"    epochs=150,\n"
"    lr=0.08,\n"
"    batch_size=512\n"
")\n"
"print(f'✅ Huấn luyện NumPy hoàn tất trong {time.time() - start_time:.2f}s')"
))

cells.append(md(
"### 1.4. Đánh giá mô hình NumPy trên Test set"
))
cells.append(code(
"numpy_test_pred = nn_numpy.predict(X_test)\n"
"numpy_test_prob = nn_numpy.predict_proba(X_test).ravel()\n"
"\n"
"numpy_metrics = {\n"
"    'name': 'NumPy MLP (8->16->8->1)',\n"
"    'test_acc': accuracy_score(y_test, numpy_test_pred),\n"
"    'test_prec': precision_score(y_test, numpy_test_pred, zero_division=0),\n"
"    'test_rec': recall_score(y_test, numpy_test_pred, zero_division=0),\n"
"    'test_f1': f1_score(y_test, numpy_test_pred, zero_division=0),\n"
"    'test_auc': roc_auc_score(y_test, numpy_test_prob)\n"
"}\n"
"\n"
"print('=== Kết quả NumPy Neural Network trên TEST SET ===')\n"
"for k, v in numpy_metrics.items():\n"
"    if k != 'name':\n"
"        print(f\"  {k:10s}: {v:.4f}\")\n"
"\n"
"print('\\nClassification Report:')\n"
"print(classification_report(y_test, numpy_test_pred, target_names=['No Diabetes', 'Diabetes']))"
))

# ============================================================
# PART 2: PYTORCH EXPERIMENTS
# ============================================================
cells.append(md(
"---\n"
"# PHẦN 2: CÁC THÍ NGHIỆM BẮT BUỘC VỚI PYTORCH\n"
"\n"
"*(Tham chiếu: Slide `intel_sys_dev_slide_03.pdf`, trang 34)*\n"
"\n"
"Slide yêu cầu thực hiện ít nhất **3 thí nghiệm có kiểm soát**:\n"
"1. **Thí nghiệm 1 — Baseline MLP:** $d \\to 64 \\to C$ (1 hidden layer)\n"
"2. **Thí nghiệm 2 — Deeper MLP:** $d \\to 64 \\to 32 \\to C$ (2 hidden layers)\n"
"3. **Thí nghiệm 3 — Optimization Experiment:** So sánh các Learning Rate và Optimizer khác nhau (Adam lr=0.001 vs Adam lr=0.01 vs SGD lr=0.01)\n"
"\n"
"Mỗi thí nghiệm cần báo cáo:\n"
"- Kiến trúc (Architecture) & số tham số (Number of parameters)\n"
"- Cấu hình huấn luyện (Training configuration)\n"
"- Đường cong huấn luyện/validation (Learning curves)\n"
"- Các chỉ số đánh giá trên tập test (Test metrics)\n"
"- Phân tích ý nghĩa (Interpretation)"
))

cells.append(md(
"### 2.1. Chuẩn bị DataLoader (PyTorch)"
))
cells.append(code(
"# Chuyển sang PyTorch Tensor\n"
"X_train_t = torch.tensor(X_train_res, dtype=torch.float32)\n"
"y_train_t = torch.tensor(y_train_res.values if hasattr(y_train_res, 'values') else y_train_res, dtype=torch.long)\n"
"\n"
"X_val_t = torch.tensor(X_val, dtype=torch.float32)\n"
"y_val_t = torch.tensor(y_val.values if hasattr(y_val, 'values') else y_val, dtype=torch.long)\n"
"\n"
"X_test_t = torch.tensor(X_test, dtype=torch.float32)\n"
"y_test_t = torch.tensor(y_test.values if hasattr(y_test, 'values') else y_test, dtype=torch.long)\n"
"\n"
"BATCH_SIZE = 256\n"
"\n"
"train_loader = DataLoader(TensorDataset(X_train_t, y_train_t), batch_size=BATCH_SIZE, shuffle=True)\n"
"val_loader = DataLoader(TensorDataset(X_val_t, y_val_t), batch_size=BATCH_SIZE, shuffle=False)\n"
"test_loader = DataLoader(TensorDataset(X_test_t, y_test_t), batch_size=BATCH_SIZE, shuffle=False)\n"
"\n"
"print(f'DataLoader ready: {len(train_loader)} batches per epoch (batch_size={BATCH_SIZE})')"
))

cells.append(md(
"### 2.2. Định nghĩa các kiến trúc MLP PyTorch\n"
"\n"
"Tạo 2 class mô hình theo đúng slide:\n"
"- `BaselineMLP`: $d \\to 64 \\to 2$\n"
"- `DeeperMLP`: $d \\to 64 \\to 32 \\to 2$"
))
cells.append(code(
"class BaselineMLP(nn.Module):\n"
"    \"\"\"Thí nghiệm 1: Baseline MLP (d -> 64 -> C)\"\"\"\n"
"    def __init__(self, input_dim=8, num_classes=2):\n"
"        super().__init__()\n"
"        self.network = nn.Sequential(\n"
"            nn.Linear(input_dim, 64),\n"
"            nn.ReLU(),\n"
"            nn.Linear(64, num_classes)\n"
"        )\n"
"    def forward(self, x):\n"
"        return self.network(x)\n"
"\n"
"class DeeperMLP(nn.Module):\n"
"    \"\"\"Thí nghiệm 2: Deeper MLP (d -> 64 -> 32 -> C)\"\"\"\n"
"    def __init__(self, input_dim=8, num_classes=2):\n"
"        super().__init__()\n"
"        self.network = nn.Sequential(\n"
"            nn.Linear(input_dim, 64),\n"
"            nn.ReLU(),\n"
"            nn.Linear(64, 32),\n"
"            nn.ReLU(),\n"
"            nn.Linear(32, num_classes)\n"
"        )\n"
"    def forward(self, x):\n"
"        return self.network(x)\n"
"\n"
"def count_parameters(model):\n"
"    return sum(p.numel() for p in model.parameters() if p.requires_grad)\n"
"\n"
"m1 = BaselineMLP(input_dim=8, num_classes=2)\n"
"m2 = DeeperMLP(input_dim=8, num_classes=2)\n"
"\n"
"print(f'Baseline MLP parameters: {count_parameters(m1)}')\n"
"print(f'Deeper MLP parameters:   {count_parameters(m2)}')"
))

cells.append(md(
"### 2.3. Hàm huấn luyện PyTorch chuẩn (Training Loop theo slide)"
))
cells.append(code(
"def train_pytorch_model(model, train_loader, val_loader, optimizer, criterion, epochs=30, name='Model'):\n"
"    \"\"\"\n"
"    Vòng lặp huấn luyện chuẩn theo Slide 18-24:\n"
"    zero_grad -> forward -> loss -> backward -> optimizer.step\n"
"    \"\"\"\n"
"    history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}\n"
"    best_val_loss = float('inf')\n"
"    best_weights = None\n"
"    \n"
"    print(f'=== Training {name} ({epochs} epochs) ===')\n"
"    start = time.time()\n"
"    \n"
"    for epoch in range(1, epochs + 1):\n"
"        # 1. Training mode\n"
"        model.train()\n"
"        train_loss, train_correct, total_train = 0.0, 0, 0\n"
"        for X_b, y_b in train_loader:\n"
"            optimizer.zero_grad()\n"
"            outputs = model(X_b)\n"
"            loss = criterion(outputs, y_b)\n"
"            loss.backward()\n"
"            optimizer.step()\n"
"            \n"
"            train_loss += loss.item() * X_b.size(0)\n"
"            preds = outputs.argmax(dim=1)\n"
"            train_correct += (preds == y_b).sum().item()\n"
"            total_train += X_b.size(0)\n"
"            \n"
"        # 2. Evaluation mode\n"
"        model.eval()\n"
"        val_loss, val_correct, total_val = 0.0, 0, 0\n"
"        with torch.no_grad():\n"
"            for X_b, y_b in val_loader:\n"
"                outputs = model(X_b)\n"
"                loss = criterion(outputs, y_b)\n"
"                val_loss += loss.item() * X_b.size(0)\n"
"                preds = outputs.argmax(dim=1)\n"
"                val_correct += (preds == y_b).sum().item()\n"
"                total_val += X_b.size(0)\n"
"                \n"
"        tr_l = train_loss / total_train\n"
"        tr_a = train_correct / total_train\n"
"        v_l = val_loss / total_val\n"
"        v_a = val_correct / total_val\n"
"        \n"
"        history['train_loss'].append(tr_l)\n"
"        history['train_acc'].append(tr_a)\n"
"        history['val_loss'].append(v_l)\n"
"        history['val_acc'].append(v_a)\n"
"        \n"
"        if v_l < best_val_loss:\n"
"            best_val_loss = v_l\n"
"            best_weights = model.state_dict().copy()\n"
"            \n"
"        if epoch % 5 == 0 or epoch == 1:\n"
"            print(f\"Epoch {epoch:2d}/{epochs} | Train Loss: {tr_l:.4f}, Acc: {tr_a:.4f} | Val Loss: {v_l:.4f}, Acc: {v_a:.4f}\")\n"
"            \n"
"    # Nạp trọng số tốt nhất\n"
"    if best_weights is not None:\n"
"        model.load_state_dict(best_weights)\n"
"    print(f'Done in {time.time() - start:.2f}s. Best Val Loss: {best_val_loss:.4f}\\n')\n"
"    \n"
"    return history\n"
"\n"
"def evaluate_pytorch_model(model, test_loader, y_test, name='Model'):\n"
"    \"\"\"Đánh giá mô hình PyTorch trên tập Test.\"\"\"\n"
"    model.eval()\n"
"    all_probs = []\n"
"    all_preds = []\n"
"    \n"
"    with torch.no_grad():\n"
"        for X_b, _ in test_loader:\n"
"            logits = model(X_b)\n"
"            probs = torch.softmax(logits, dim=1)[:, 1]\n"
"            preds = logits.argmax(dim=1)\n"
"            all_probs.extend(probs.numpy())\n"
"            all_preds.extend(preds.numpy())\n"
"            \n"
"    all_probs = np.array(all_probs)\n"
"    all_preds = np.array(all_preds)\n"
"    y_true = y_test.values if hasattr(y_test, 'values') else y_test\n"
"    \n"
"    results = {\n"
"        'name': name,\n"
"        'test_acc': accuracy_score(y_true, all_preds),\n"
"        'test_prec': precision_score(y_true, all_preds, zero_division=0),\n"
"        'test_rec': recall_score(y_true, all_preds, zero_division=0),\n"
"        'test_f1': f1_score(y_true, all_preds, zero_division=0),\n"
"        'test_auc': roc_auc_score(y_true, all_probs),\n"
"        'y_pred': all_preds,\n"
"        'y_prob': all_probs,\n"
"        'model': model\n"
"    }\n"
"    return results"
))

cells.append(md(
"### 2.4. Thí nghiệm 1: Baseline MLP ($d \\to 64 \\to C$)\n"
"\n"
"- **Kiến trúc:** Input (8) $\\to$ Linear(8, 64) $\\to$ ReLU $\\to$ Linear(64, 2)\n"
"- **Optimizer:** Adam ($lr = 0.001$)\n"
"- **Loss:** CrossEntropyLoss"
))
cells.append(code(
"torch.manual_seed(RANDOM_STATE)\n"
"exp1_model = BaselineMLP(input_dim=8, num_classes=2)\n"
"exp1_opt = optim.Adam(exp1_model.parameters(), lr=0.001)\n"
"criterion = nn.CrossEntropyLoss()\n"
"\n"
"exp1_history = train_pytorch_model(\n"
"    exp1_model, train_loader, val_loader, exp1_opt, criterion,\n"
"    epochs=15, name='Exp 1: Baseline MLP (8->64->2)'\n"
")\n"
"\n"
"exp1_results = evaluate_pytorch_model(exp1_model, test_loader, y_test, name='Exp 1: Baseline MLP (8->64->2)')\n"
"print('=== Thí nghiệm 1 Test Metrics ===')\n"
"for k, v in exp1_results.items():\n"
"    if isinstance(v, (int, float)):\n"
"        print(f\"  {k}: {v:.4f}\")"
))

cells.append(md(
"### 2.5. Thí nghiệm 2: Deeper MLP ($d \\to 64 \\to 32 \\to C$)\n"
"\n"
"- **Kiến trúc:** Input (8) $\\to$ Linear(8, 64) $\\to$ ReLU $\\to$ Linear(64, 32) $\\to$ ReLU $\\to$ Linear(32, 2)\n"
"- **Optimizer:** Adam ($lr = 0.001$)\n"
"- **Loss:** CrossEntropyLoss\n"
"- **Mục đích:** Đánh giá việc tăng độ sâu (depth) mạng có cải thiện biểu diễn và độ chính xác không."
))
cells.append(code(
"torch.manual_seed(RANDOM_STATE)\n"
"exp2_model = DeeperMLP(input_dim=8, num_classes=2)\n"
"exp2_opt = optim.Adam(exp2_model.parameters(), lr=0.001)\n"
"\n"
"exp2_history = train_pytorch_model(\n"
"    exp2_model, train_loader, val_loader, exp2_opt, criterion,\n"
"    epochs=15, name='Exp 2: Deeper MLP (8->64->32->2)'\n"
")\n"
"\n"
"exp2_results = evaluate_pytorch_model(exp2_model, test_loader, y_test, name='Exp 2: Deeper MLP (8->64->32->2)')\n"
"print('=== Thí nghiệm 2 Test Metrics ===')\n"
"for k, v in exp2_results.items():\n"
"    if isinstance(v, (int, float)):\n"
"        print(f\"  {k}: {v:.4f}\")"
))

cells.append(md(
"### 2.6. Thí nghiệm 3: Thử nghiệm tối ưu hoá (Optimization Experiment)\n"
"\n"
"So sánh **3 cấu hình tối ưu** trên kiến trúc Deeper MLP:\n"
"1. **Config A:** Adam, $lr = 0.001$ (chuẩn)\n"
"2. **Config B:** Adam, $lr = 0.01$ (learning rate cao hơn)\n"
"3. **Config C:** SGD with momentum (momentum=0.9), $lr = 0.01$"
))
cells.append(code(
"# Config B: Adam lr=0.01\n"
"torch.manual_seed(RANDOM_STATE)\n"
"exp3_model_b = DeeperMLP(input_dim=8, num_classes=2)\n"
"exp3_opt_b = optim.Adam(exp3_model_b.parameters(), lr=0.01)\n"
"exp3_hist_b = train_pytorch_model(exp3_model_b, train_loader, val_loader, exp3_opt_b, criterion, epochs=15, name='Exp 3B: Adam (lr=0.01)')\n"
"exp3_res_b = evaluate_pytorch_model(exp3_model_b, test_loader, y_test, name='Exp 3B: Adam (lr=0.01)')\n"
"\n"
"# Config C: SGD momentum=0.9, lr=0.01\n"
"torch.manual_seed(RANDOM_STATE)\n"
"exp3_model_c = DeeperMLP(input_dim=8, num_classes=2)\n"
"exp3_opt_c = optim.SGD(exp3_model_c.parameters(), lr=0.01, momentum=0.9)\n"
"exp3_hist_c = train_pytorch_model(exp3_model_c, train_loader, val_loader, exp3_opt_c, criterion, epochs=15, name='Exp 3C: SGD (lr=0.01, mom=0.9)')\n"
"exp3_res_c = evaluate_pytorch_model(exp3_model_c, test_loader, y_test, name='Exp 3C: SGD (lr=0.01, mom=0.9)')"
))

cells.append(md(
"### 2.7. So sánh các thí nghiệm PyTorch & Learning Curves"
))
cells.append(code(
"# Tổng hợp kết quả các thí nghiệm\n"
"exp_table = pd.DataFrame([{\n"
"    'Experiment': r['name'],\n"
"    'Parameters': count_parameters(r['model']),\n"
"    'Test Acc': r['test_acc'],\n"
"    'Test Precision': r['test_prec'],\n"
"    'Test Recall': r['test_rec'],\n"
"    'Test F1': r['test_f1'],\n"
"    'Test AUC': r['test_auc'],\n"
"} for r in [exp1_results, exp2_results, exp3_res_b, exp3_res_c]])\n"
"\n"
"print('=== TỔNG HỢP CÁC THÍ NGHIỆM PYTORCH ===')\n"
"print(exp_table.to_string(index=False))"
))

cells.append(code(
"# Vẽ Learning Curves so sánh Thí nghiệm 1 vs 2 vs 3B vs 3C\n"
"fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
"\n"
"hists = [\n"
"    ('Baseline (Adam 0.001)', exp1_history, '#1f77b4'),\n"
"    ('Deeper (Adam 0.001)', exp2_history, '#2ca02c'),\n"
"    ('Deeper (Adam 0.01)', exp3_hist_b, '#ff7f0e'),\n"
"    ('Deeper (SGD 0.01)', exp3_hist_c, '#d62728'),\n"
"]\n"
"\n"
"for label, h, col in hists:\n"
"    axes[0].plot(h['val_loss'], label=f'{label} (Val)', color=col, lw=2)\n"
"    axes[1].plot(h['val_acc'], label=f'{label} (Val)', color=col, lw=2)\n"
"\n"
"axes[0].set_title('Validation Loss across Experiments')\n"
"axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Loss'); axes[0].legend()\n"
"\n"
"axes[1].set_title('Validation Accuracy across Experiments')\n"
"axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Accuracy'); axes[1].legend()\n"
"\n"
"plt.tight_layout(); plt.show()"
))

# ============================================================
# PART 3: REPRESENTATION LEARNING
# ============================================================
cells.append(md(
"---\n"
"# PHẦN 3: KHÁM PHÁ BIỂU DIỄN ẨN (REPRESENTATION LEARNING)\n"
"\n"
"*(Tham chiếu: Slide `intel_sys_dev_slide_03.pdf`, trang 31: 'Inspecting the Learned Representation')*\n"
"\n"
"Slide đặt câu hỏi quan trọng:\n"
"> *\"What does a neural network actually learn?\"*\n"
"> *\"Do observations from different classes separate in the learned space?\"*\n"
"\n"
"Ta sẽ trích xuất vector biểu diễn $h_1 \\in \\mathbb{R}^{64}$ và $h_2 \\in \\mathbb{R}^{32}$ từ các hidden layers của mô hình `DeeperMLP`, sau đó dùng **PCA** để chiếu xuống không gian 2D và quan sát xem các điểm thuộc 2 lớp (No Diabetes vs Diabetes) phân tách như thế nào so với không gian đặc trưng ban đầu."
))

cells.append(code(
"from sklearn.decomposition import PCA\n"
"\n"
"# Trích xuất biểu diễn từ DeeperMLP\n"
"best_dl_model = exp2_model\n"
"best_dl_model.eval()\n"
"\n"
"# Lấy một sample 2000 điểm từ test set để visualize\n"
"sample_idx = np.random.choice(len(X_test), size=min(2000, len(X_test)), replace=False)\n"
"X_sample = X_test_t[sample_idx]\n"
"y_sample = y_test.values[sample_idx] if hasattr(y_test, 'values') else y_test[sample_idx]\n"
"\n"
"with torch.no_grad():\n"
"    # Trích xuất từng layer\n"
"    h1 = best_dl_model.network[1](best_dl_model.network[0](X_sample)).numpy()  # 64-dim\n"
"    h2 = best_dl_model.network[3](best_dl_model.network[2](torch.tensor(h1))).numpy()  # 32-dim\n"
"\n"
"print('Kích thước biểu diễn:')\n"
"print('  Không gian ban đầu X:', X_sample.shape)\n"
"print('  Biểu diễn Layer 1 h1:', h1.shape)\n"
"print('  Biểu diễn Layer 2 h2:', h2.shape)"
))

cells.append(code(
"# Chiếu PCA 2D\n"
"pca_orig = PCA(n_components=2).fit_transform(X_sample.numpy())\n"
"pca_h1 = PCA(n_components=2).fit_transform(h1)\n"
"pca_h2 = PCA(n_components=2).fit_transform(h2)\n"
"\n"
"fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n"
"\n"
"for ax, data_2d, title in [\n"
"    (axes[0], pca_orig, '1. Không gian gốc X (8 features)'),\n"
"    (axes[1], pca_h1, '2. Learned Representation Layer 1 (64-dim -> 2D)'),\n"
"    (axes[2], pca_h2, '3. Learned Representation Layer 2 (32-dim -> 2D)'),\n"
"]:\n"
"    scatter = ax.scatter(data_2d[:, 0], data_2d[:, 1], c=y_sample, cmap='coolwarm', alpha=0.6, s=20)\n"
"    ax.set_title(title)\n"
"    ax.set_xlabel('PCA Component 1')\n"
"    ax.set_ylabel('PCA Component 2')\n"
"\n"
"# Legend\n"
"handles, _ = scatter.legend_elements()\n"
"axes[2].legend(handles, ['Không tiểu đường (0)', 'Tiểu đường (1)'], loc='best')\n"
"\n"
"plt.suptitle('Sự phân tách của các lớp qua các tầng biểu diễn ẩn (Learned Representations)', fontsize=14, y=1.02)\n"
"plt.tight_layout(); plt.show()"
))

cells.append(md(
"### 3.1. Nhận xét về Representation Learning:\n"
"- Ở **không gian gốc X (8 chiều)**: các điểm của 2 lớp phân bố chồng lấn, biên phân chia phức tạp.\n"
"- Qua **Layer 1 ($h_1 \\in \\mathbb{R}^{64}$)** và **Layer 2 ($h_2 \\in \\mathbb{R}^{32}$)**: mạng nơ-ron học phép biến đổi phi tuyến (nonlinear transformation) giúp gom cụm và phân tách 2 lớp rõ ràng hơn.\n"
"- Điều này minh chứng luận điểm cốt lõi của slide: **Deep Learning = Học biểu diễn (Representation Learning) + Dự đoán**."
))

# ============================================================
# PART 4: SAVE BEST PYTORCH MODEL
# ============================================================
cells.append(md(
"---\n"
"# PHẦN 4: LƯU MÔ HÌNH VÀ KẾT QUẢ\n"
"\n"
"Lưu mô hình PyTorch tốt nhất (`.pth`) theo đúng hướng dẫn Slide trang 33:\n"
"```python\n"
"torch.save(model.state_dict(), 'mlp_model.pth')\n"
"```"
))

cells.append(code(
"# Chọn mô hình tốt nhất (Exp 2 - Deeper MLP)\n"
"BEST_MODEL_PATH = os.path.join(MODEL_DIR, 'diabetes_mlp_best.pth')\n"
"torch.save(best_dl_model.state_dict(), BEST_MODEL_PATH)\n"
"print(f'✅ Đã lưu trọng số mô hình PyTorch tốt nhất vào: {BEST_MODEL_PATH}')\n"
"\n"
"# Lưu metadata mô hình\n"
"dl_metadata = {\n"
"    'architecture': 'DeeperMLP (8 -> 64 -> 32 -> 2)',\n"
"    'input_dim': 8,\n"
"    'hidden1': 64,\n"
"    'hidden2': 32,\n"
"    'num_classes': 2,\n"
"    'optimizer': 'Adam',\n"
"    'learning_rate': 0.001,\n"
"    'batch_size': BATCH_SIZE,\n"
"    'epochs': 15,\n"
"    'test_metrics': {\n"
"        'accuracy': exp2_results['test_acc'],\n"
"        'precision': exp2_results['test_prec'],\n"
"        'recall': exp2_results['test_rec'],\n"
"        'f1_score': exp2_results['test_f1'],\n"
"        'auc_roc': exp2_results['test_auc']\n"
"    }\n"
"}\n"
"joblib.dump(dl_metadata, os.path.join(MODEL_DIR, 'diabetes_dl_metadata.pkl'))\n"
"\n"
"# Lưu kết quả dự đoán test của DL để so sánh ở notebook 4\n"
"np.savez_compressed(\n"
"    os.path.join(MODEL_DIR, 'diabetes_dl_predictions.npz'),\n"
"    y_pred=exp2_results['y_pred'],\n"
"    y_prob=exp2_results['y_prob'],\n"
"    numpy_pred=numpy_test_pred,\n"
"    numpy_prob=numpy_test_prob\n"
")\n"
"print('✅ Đã lưu kết quả dự đoán phục vụ so sánh.')"
))

cells.append(md(
"## 5. Kết luận\n"
"\n"
"1. **NumPy Implementation**: Đã tự xây dựng mạng $8 \\to 16 \\to 8 \\to 1$ thuần NumPy, thực hiện thành công forward propagation, binary cross-entropy, backpropagation với chain rule và gradient descent.\n"
"2. **PyTorch Experiments**: Đã thực hiện đầy đủ **3 thí nghiệm bắt buộc**:\n"
"   - Baseline MLP ($8 \\to 64 \\to 2$)\n"
"   - Deeper MLP ($8 \\to 64 \\to 32 \\to 2$)\n"
"   - Optimization experiment (Adam lr=0.001 vs Adam lr=0.01 vs SGD)\n"
"3. **Representation Learning**: Đã trực quan hoá $h_1, h_2$ qua PCA và chứng minh không gian ẩn giúp phân tách lớp tốt hơn không gian ban đầu.\n"
"4. **Mô hình tốt nhất** (`diabetes_mlp_best.pth`) đã được lưu cùng metadata.\n"
"\n"
"**Tiếp theo: Notebook 4 — So sánh khoa học giữa 3 mô hình ML cơ bản và mô hình Deep Learning.**"
))

nb = {"cells": cells, "metadata": {
    "kernelspec": {"display_name": "Python 3 (ipykernel)", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.11.16"}
}, "nbformat": 4, "nbformat_minor": 5}

out = os.path.join(os.path.dirname(__file__), '3_deep_learning.ipynb')
with open(out, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print('Saved', out)
